### ISSUE TITLE
能否支持Kerwin1202/chatgpt-web | Chanzhaoyu/chatgpt-web的反向代理

### ISSUE THREAD

**Issue by CLAY-CMD** [flyingpot/chatgpt-proxy#1]

**Comment by spoonnotfound** [comment]
> 使用 accessToken 时，不管你是国内还是国外的机器，都会使用代理。默认代理为 [pengzhile](https://github.com/pengzhile) 大佬的 [https://ai.fakeopen.com](https://ai.fakeopen.com)，这不是后门也不是监听，除非你有能力自己翻过 CF 验证，用前请知悉。[社区代理](https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy)（注意：只有这两个是推荐，其他第三方来源，请自行甄别）

按照这段描述，大概率是支持的。因为本项目本身就是[https://ai.fakeopen.com](https://ai.fakeopen.com)代理的替代版本

**Comment by maxduke** [comment]
```
chatgpt-proxy  | 2023/06/24 12:09:40 Request failed with status code: 401, status: Unauthorized, body: {"detail":{"message":"Unauthorized - Access token is missing"}}
```
用web-share最新版会报以上错误，地址填的是 https://chatgpt-proxy-url/api/

**Comment by JamesFlare1212** [comment]
你填Access Token了吗？

**Comment by maxduke** [comment]
> 你填Access Token了吗？

😂肯定呀，同样配置同样程序，用go那个或者fake那个都正常

**Comment by spoonnotfound** [comment]
@maxduke 你可以用最新版本试下，应该是header兼容的问题。Pandora是会用X-Authorization这个值传access token的，chatgpt-web-share传的是Authorization

**Comment by maxduke** [comment]
> 

最新版测试可用，多谢

**Comment by CLAY-CMD** [comment]
> > 使用 accessToken 时，不管你是国内还是国外的机器，都会使用代理。默认代理为 [pengzhile](https://github.com/pengzhile) 大佬的 https://ai.fakeopen.com，这不是后门也不是监听，除非你有能力自己翻过 CF 验证，用前请知悉。[社区代理](https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy)（注意：只有这两个是推荐，其他第三方来源，请自行甄别）
> 
> 按照这段描述，大概率是支持的。因为本项目本身就是https://ai.fakeopen.com代理的替代版本

好的，我已经成功调用了
