### ISSUE TITLE
前端支持

### ISSUE THREAD

**Issue by eureka6** [flyingpot/chatgpt-proxy#2]
1.你好，请问一下，本项目参考了[linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)，那么对前端项目[moeakwak/chatgpt-web-share](https://github.com/moeakwak/chatgpt-web-share)的支持程度怎么样呢？

2.访问`反代地址`也就是`CHATGPT_BASE_URL`用的是哪个地址呀？

**Comment by spoonnotfound** [comment]
1.我没有试验过，但是这个[issue](https://github.com/flyingpot/chatgpt-proxy/issues/1)里有老哥验证过可以用
2.配置成本项目部署后的域名即可

**Comment by eureka6** [comment]
好的，这去试一试

**Comment by eureka6** [comment]
前端部署了[moeakwak/chatgpt-web-share](https://github.com/moeakwak/chatgpt-web-share)，其中`CHATGPT_BASE_URL`填入`https://chatgpt-proxy.xxx.com/api/`地址，成功。

**Comment by eureka6** [comment]
谢谢大佬！
