### ISSUE TITLE
vercel部署问题

### ISSUE THREAD

**Issue by 18230** [flyingpot/chatgpt-proxy#4]
vercel为什么不行，请求不反应，不知道为啥

**Comment by spoonnotfound** [comment]
是的，Vercel支持不了，现在flush会报错。原因可以参考https://github.com/vercel/go-bridge/issues/7 Vercel对于后端语言的支持没有前端好

**Comment by 18230** [comment]
老哥有没有什么折中的办法，我应用都在vercel上，这样比较方便，速度上也有优势

**Comment by spoonnotfound** [comment]
那只能重写一个js的版本了，暂时没啥别的办法
