### ISSUE TITLE
更新方法

### ISSUE THREAD

**Issue by eureka6** [flyingpot/chatgpt-proxy#5]
1. 刚看到大佬发布了新版本，而我是在一台Windows电脑上用`go build`部署的，请问如果我要更新到最新版，是不是需要重新下载解压出来文件夹，再进入文件夹，然后运行`go build`部署？
2. 怎么指定端口呀？用`cmd`在文件夹里运行`PORT=8080 ./chatgpt-proxy`提示`PORT不是命令`

**Comment by spoonnotfound** [comment]
1.是的
2.PORT=8080 ./chatgpt-proxy是linux下运行的命令。windows下可以直接运行chatgpt-proxy，默认端口8080。建议使用docker来运行
