### ISSUE TITLE
GPT-4 会提示 status:403 Forbidden

### ISSUE THREAD

**Issue by git-syl** [flyingpot/chatgpt-proxy#8]
看日志提示：
2023/06/28 03:04:11 Request failed with status code: 403, status: Forbidden, body: {"detail":"Our systems have detected unusual activity from your system. Please try again later."}

请问这是不是OpenAi开始检测了？看日志发现很多403了，昨天还可以用的。

**Comment by spoonnotfound** [comment]
升级到最新版本试试呢

**Comment by spoonnotfound** [comment]
我这边测试正常。昨天正常是因为OpenAI昨天关闭了对于arkose token的校验，而当时的版本是有问题的。现在问题已经修复。

**Comment by git-syl** [comment]
> 我这边测试正常。昨天正常是因为OpenAI昨天关闭了对于arkose token的校验，而当时的版本是有问题的。现在问题已经修复。

非常谢谢，确实是版本问题。升级就好了。
